// Default beautiful HTML email master templates.
// These are TipTap-schema-compatible (paragraph alignment + inline span styles).
// Load them via the "Load defaults" button in the master template section.

const YEAR = new Date().getFullYear()

export const DEFAULT_EMAIL_HEADER: Record<'pt' | 'en', string> = {
  pt: [
    '<p style="text-align: center"><span style="font-size: 36px">🏠</span></p>',
    '<p style="text-align: center"><strong><span style="font-size: 24px; color: #1e40af">RentFlow</span></strong></p>',
    '<p style="text-align: center"><span style="font-size: 13px; color: #64748b">Sistema de Gestão de Propriedades</span></p>',
    '<p style="text-align: center"><span style="font-size: 11px; color: #94a3b8">▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬</span></p>',
    '<p></p>',
  ].join(''),

  en: [
    '<p style="text-align: center"><span style="font-size: 36px">🏠</span></p>',
    '<p style="text-align: center"><strong><span style="font-size: 24px; color: #1e40af">RentFlow</span></strong></p>',
    '<p style="text-align: center"><span style="font-size: 13px; color: #64748b">Property Management System</span></p>',
    '<p style="text-align: center"><span style="font-size: 11px; color: #94a3b8">▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬</span></p>',
    '<p></p>',
  ].join(''),
}

export const DEFAULT_EMAIL_FOOTER: Record<'pt' | 'en', string> = {
  pt: [
    '<p></p>',
    '<p style="text-align: center"><span style="font-size: 11px; color: #94a3b8">▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬</span></p>',
    '<p style="text-align: center"><span style="font-size: 12px; color: #64748b">Esta mensagem foi gerada automaticamente pelo <strong>RentFlow</strong>.</span></p>',
    '<p style="text-align: center"><span style="font-size: 12px; color: #64748b">Por favor, não responda este e-mail.</span></p>',
    '<p style="text-align: center"><span style="font-size: 11px; color: #94a3b8">© ' + YEAR + ' RentFlow · Sistema de Gestão de Propriedades</span></p>',
  ].join(''),

  en: [
    '<p></p>',
    '<p style="text-align: center"><span style="font-size: 11px; color: #94a3b8">▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬</span></p>',
    '<p style="text-align: center"><span style="font-size: 12px; color: #64748b">This message was automatically generated by <strong>RentFlow</strong>.</span></p>',
    '<p style="text-align: center"><span style="font-size: 12px; color: #64748b">Please do not reply to this email.</span></p>',
    '<p style="text-align: center"><span style="font-size: 11px; color: #94a3b8">© ' + YEAR + ' RentFlow · Property Management System</span></p>',
  ].join(''),
}
